# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrisbanePoker' do
inhibit_all_warnings!
use_frameworks!

  # Pods for BrisbanePoker
pod 'Alamofire', '~> 4.7.0'
pod 'SwiftyJSON', '~> 4.0.0'
pod 'SwiftSpinner'
pod 'Firebase/Messaging'
pod 'Firebase/Core'

end
